name: Singlebox

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest
    # runs-on: [self-hosted, macOS, X64]

    steps:
    - uses: actions/checkout@v2
    - name: Get Neutron version
      run: echo NEUTRON_VERSION=$(cat neutron-version $1) >> $GITHUB_ENV
    - uses: actions/checkout@v2
      with:
        repository: 'webcatalog/neutron'
        ref: v${{ env.NEUTRON_VERSION }}
        path: 'neutron'
        fetch-depth: 1
        submodules: false
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Get tag name
      run: echo CI_BUILD_TAG=${GITHUB_REF/refs\/tags\//} >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/')
    - name: Build Singlebox
      run: |
        cp apps/singlebox/config.json neutron/
        cp -r apps/singlebox/build-resources-mas neutron
        cp build-mas.js neutron
        cd neutron
        yarn --prefer-offline --network-timeout 600000
        yarn lint
        yarn build
        node build-mas.js
      env:
        CI: true
        CI_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        CSC_LINK: ${{ secrets.CSC_LINK }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REACT_APP_AMPLITUDE_API_KEY: ${{ secrets.REACT_APP_AMPLITUDE_API_KEY }}
        REACT_APP_SWIFTYPE_HOST_ID: ${{ secrets.REACT_APP_SWIFTYPE_HOST_ID }}
        REACT_APP_SWIFTYPE_SEARCH_KEY: ${{ secrets.REACT_APP_SWIFTYPE_SEARCH_KEY }}
        REACT_APP_SWIFTYPE_ENGINE_NAME: ${{ secrets.REACT_APP_SWIFTYPE_ENGINE_NAME }}
        ELECTRON_APP_SENTRY_DSN: ${{ secrets.ELECTRON_APP_SENTRY_DSN }}
      if: startsWith(github.ref, 'refs/tags/')
